#!/usr/bin/env python3

import os
import sys
import re
import time
import ctypes
import shutil
import pathlib
import argparse
import subprocess

# On Windows, this should point to the directory where SDL2.dll is stored
# os.environ["PYSDL2_DLL_PATH"] = "C:\\Users\\Home\\DLL"

import sdl2
import sdl2.ext

from collections import OrderedDict

GREEN = '\033[0;32m'
RED = '\033[0;34m'
END = '\033[0m'

KEEP_KEYS = { sdl2.SDLK_RETURN }
UNDO_KEYS = { sdl2.SDLK_BACKSPACE, sdl2.SDLK_u }
QUIT_KEYS = { sdl2.SDLK_ESCAPE, sdl2.SDLK_q }

sdl2.ext.init()


def image_generator(src, jump):
    for img_name in sorted(os.listdir(src)):
        if jump and img_name != jump:
            continue
        jump = None
        try:
            img_file = os.path.join(src, img_name)
            yield img_file, sdl2.ext.load_image(img_file)
        except (OSError, sdl2.ext.common.SDLError):
            # Can't load this file as an image - ignore it
            continue


def Action_CopyToDirectory(image_file, args):
    dest_path = os.path.join(args.dst, os.path.basename(image_file))

    print(f'{GREEN}Copying{END}: {dest_path}')

    while os.path.exists(dest_path):
        base, _, ext = dest_path.rpartition('.')
        m = re.match('(.*_)([0-9]+)', base)

        if m:
            n = int(m.groups()[1])
            base = f'{m.groups()[0]}{n+1}'
        else:
            base = f'{base}_1'

        dest_path = '.'.join([base, ext])

    shutil.copy2(image_file, dest_path)

    def undo():
        print(f'{RED}Removing{END}: {dest_path}')
        pathlib.Path.unlink(dest_path)

    return undo


class ImageDisplayer(object):
    WINDOW_SIZE = (720, 1200)

    def __init__(self, args):
        self.args = args
        self.md5s = set()
        # Initialise window
        self.window = sdl2.ext.Window('Image Sorter', self.WINDOW_SIZE)
        self.window.show()

        self.action = Action_CopyToDirectory
        self.actions = OrderedDict()

        self.undo_level = 0

        # Image generator
        self.image_file = None
        self.image = None
        self.images = image_generator(args.src, args.jump or None)
        # Show first image
        self.show_next_image()

    def find_scaled_dstrect(self, img):
        try:
            win = self.window.get_surface()
            win_dydx = win.w / win.h
            img_dydx = img.w / img.h
            if img_dydx < win_dydx:
                # Image proportions are too tall - return narrower dstrect
                sf = img_dydx / win_dydx
                dst_w = int(win.w * sf)
                dst_x = (win.w - dst_w) // 2
                return sdl2.SDL_Rect(dst_x, 0, dst_w, win.h)
            elif img_dydx > win_dydx:
                # Image proportions are too wide - return shorter dstrect
                sf = win_dydx / img_dydx
                dst_h = int(win.h * sf)
                dst_y = (win.h - dst_h) // 2
                return sdl2.SDL_Rect(0, dst_y, win.w, dst_h)
        except ZeroDivisionError:
            return None
        # Window is perfectly proportioned for image - just use default behaviour
        return None

    def show_next_image(self):
        try:
            if self.undo_level > 0:
                self.undo_level -= 1
                self.update_undo()
            else:
                while True:
                    self.image_file, self.image = next(self.images)
                    p = subprocess.run(['md5sum', self.image_file], stdout=subprocess.PIPE)
                    md5 = p.stdout.split(b' ')[0].strip()
                    if md5 in self.md5s:
                        print(f'Skipping duplicate: {self.image_file}')
                        continue
                    self.md5s.add(md5)
                    break

                self.actions[self.image_file] = None
                self.show_image()
        except StopIteration:
            return False
        return True

    def show_image(self):
        print(f'Showing: {self.image_file}')

        image = self.image

        sdl2.ext.fill(self.window.get_surface(), 0)
        sdl2.SDL_BlitScaled(image, None, self.window.get_surface(), self.find_scaled_dstrect(image))
        time.sleep(0.05)  # FIXME: It seems there's a race condiion on displaying the first image correctly...
        sdl2.SDL_UpdateWindowSurface(self.window.window)
        sdl2.SDL_FreeSurface(image)

    def action_image(self):
        print(f'Actioning: {self.image_file}')
        self.actions[self.image_file] = self.action(self.image_file, args)

    def undo(self):
        self.undo_level += 1
        self.update_undo()
        undo_action = self.actions[self.image_file]
        if undo_action is not None:
            undo_action()
            self.actions[self.image_file] = None

    def update_undo(self):
        self.image_file = list(self.actions.keys())[-self.undo_level - 1]
        self.image = sdl2.ext.load_image(self.image_file)
        self.show_image()


def run(args):
    running = True
    displayer = ImageDisplayer(args)
    event = sdl2.SDL_Event()
    while running:
        while sdl2.SDL_PollEvent(ctypes.byref(event)) != 0:
            if event.type == sdl2.SDL_QUIT:
                running = False
            elif event.type == sdl2.SDL_KEYDOWN:
                keysym = event.key.keysym.sym
                if keysym in UNDO_KEYS:
                    displayer.undo()
                elif keysym in QUIT_KEYS:
                    running = False
                else:
                    if keysym in KEEP_KEYS:
                        displayer.action_image()
                    running = displayer.show_next_image()


if __name__ == '__main__':

    cwd = os.getcwd()

    parser = argparse.ArgumentParser()
    parser.add_argument('-s', '--src', default=cwd, help='Source directory')
    parser.add_argument('-d', '--dst', default='KEEP', help='Destination directory')
    parser.add_argument('-j', '--jump', default='', help='Jump to')

    args = parser.parse_args()

    try:
        os.mkdir(args.dst)
    except FileExistsError:
        pass

    try:
        run(args)
    except Exception as e:
        print('Unexpected error:')
        import traceback
        traceback.print_exception(*sys.exc_info())

sdl2.ext.quit()
